import type { ContentItem } from "@/lib/domain/content";

export type {
  ContentItem,
  ContentStatus,
  ContentType,
  PublishingStatus,
  SidebarFilterId,
} from "@/lib/domain/content";

/** Mock library. Replaced by the content service in a later milestone. */
export const CONTENT_LIBRARY_ITEMS: readonly ContentItem[] = [
  {
    id: "cl-1",
    title: "Azure Networking Deep Dive",
    type: "article",
    status: "published",
    publishingStatus: "live",
    platforms: ["LinkedIn", "Blog"],
    tags: ["azure", "networking", "cloud"],
    author: "Aarav Mehta",
    summary:
      "A practitioner guide to VNet design, peering, and private endpoints for enterprise landing zones.",
    createdAt: "2026-06-12T09:00:00.000Z",
    updatedAt: "2026-08-01T14:20:00.000Z",
    isFavorite: true,
    thumbnailHue: 214,
  },
  {
    id: "cl-2",
    title: "Terraform Best Practices",
    type: "article",
    status: "scheduled",
    publishingStatus: "queued",
    platforms: ["LinkedIn", "X"],
    tags: ["terraform", "iac", "devops"],
    author: "Priya Nair",
    summary:
      "Module structure, state management, and CI validation patterns for multi-environment Terraform.",
    createdAt: "2026-07-04T11:30:00.000Z",
    updatedAt: "2026-08-02T06:45:00.000Z",
    isFavorite: true,
    thumbnailHue: 162,
  },
  {
    id: "cl-3",
    title: "Cloud Run Architecture",
    type: "video",
    status: "published",
    publishingStatus: "live",
    platforms: ["YouTube", "LinkedIn"],
    tags: ["gcp", "cloud-run", "serverless"],
    author: "Marcus Lee",
    summary:
      "Walkthrough of request routing, autoscaling, and VPC egress for production Cloud Run services.",
    createdAt: "2026-05-20T08:15:00.000Z",
    updatedAt: "2026-07-28T16:10:00.000Z",
    isFavorite: false,
    thumbnailHue: 28,
  },
  {
    id: "cl-4",
    title: "Kubernetes Security",
    type: "video",
    status: "draft",
    publishingStatus: "not_started",
    platforms: ["YouTube"],
    tags: ["kubernetes", "security", "zero-trust"],
    author: "Priya Nair",
    summary: "RBAC hardening, network policies, and admission control for AKS and GKE clusters.",
    createdAt: "2026-07-22T10:00:00.000Z",
    updatedAt: "2026-08-02T07:15:00.000Z",
    isFavorite: false,
    thumbnailHue: 350,
  },
  {
    id: "cl-5",
    title: "Cloud SQL HA",
    type: "poster",
    status: "published",
    publishingStatus: "live",
    platforms: ["Instagram", "LinkedIn"],
    tags: ["gcp", "database", "ha"],
    author: "Aarav Mehta",
    summary:
      "Visual explainer of regional HA, read replicas, and failover timelines for Cloud SQL.",
    createdAt: "2026-06-01T13:00:00.000Z",
    updatedAt: "2026-07-15T09:30:00.000Z",
    isFavorite: false,
    thumbnailHue: 199,
  },
  {
    id: "cl-6",
    title: "IAM Best Practices",
    type: "article",
    status: "draft",
    publishingStatus: "not_started",
    platforms: ["Blog"],
    tags: ["iam", "security", "azure"],
    author: "Marcus Lee",
    summary:
      "Least privilege, conditional access, and break-glass patterns for cloud identity at scale.",
    createdAt: "2026-07-30T15:45:00.000Z",
    updatedAt: "2026-08-01T11:00:00.000Z",
    isFavorite: false,
    thumbnailHue: 265,
  },
  {
    id: "cl-7",
    title: "Spring Launch Hero Poster",
    type: "poster",
    status: "scheduled",
    publishingStatus: "queued",
    platforms: ["Instagram", "Facebook", "LinkedIn"],
    tags: ["campaign", "launch", "brand"],
    author: "Aarav Mehta",
    summary: "Primary campaign visual for the Spring product launch across social channels.",
    createdAt: "2026-07-18T09:20:00.000Z",
    updatedAt: "2026-08-02T05:00:00.000Z",
    isFavorite: true,
    thumbnailHue: 312,
  },
  {
    id: "cl-8",
    title: "Product Demo Thumbnail Set",
    type: "thumbnail",
    status: "published",
    publishingStatus: "live",
    platforms: ["YouTube", "TikTok"],
    tags: ["thumbnail", "video", "brand"],
    author: "Priya Nair",
    summary: "Three aspect-ratio variants optimised for YouTube and short-form vertical video.",
    createdAt: "2026-06-25T12:00:00.000Z",
    updatedAt: "2026-07-20T18:40:00.000Z",
    isFavorite: false,
    thumbnailHue: 45,
  },
  {
    id: "cl-9",
    title: "Q3 Newsletter Intro",
    type: "article",
    status: "archived",
    publishingStatus: "live",
    platforms: ["Blog"],
    tags: ["newsletter", "q3"],
    author: "Priya Nair",
    summary:
      "Opening section for the Q3 customer newsletter with key metrics and roadmap highlights.",
    createdAt: "2026-04-10T08:00:00.000Z",
    updatedAt: "2026-05-01T10:00:00.000Z",
    isFavorite: false,
    thumbnailHue: 180,
  },
  {
    id: "cl-10",
    title: "Zero Trust Overview Reel",
    type: "video",
    status: "scheduled",
    publishingStatus: "queued",
    platforms: ["Instagram", "TikTok"],
    tags: ["security", "reel", "education"],
    author: "Marcus Lee",
    summary: "60-second reel explaining zero trust principles for a technical audience.",
    createdAt: "2026-07-29T14:30:00.000Z",
    updatedAt: "2026-08-02T08:00:00.000Z",
    isFavorite: false,
    thumbnailHue: 330,
  },
  {
    id: "cl-11",
    title: "Webinar Registration Poster",
    type: "poster",
    status: "draft",
    publishingStatus: "not_started",
    platforms: ["LinkedIn", "X"],
    tags: ["webinar", "event"],
    author: "Aarav Mehta",
    summary: "Registration creative for the August cloud architecture webinar series.",
    createdAt: "2026-08-01T09:00:00.000Z",
    updatedAt: "2026-08-02T09:30:00.000Z",
    isFavorite: false,
    thumbnailHue: 220,
  },
  {
    id: "cl-12",
    title: "Cost Optimisation Cheat Sheet",
    type: "thumbnail",
    status: "published",
    publishingStatus: "live",
    platforms: ["LinkedIn", "Instagram"],
    tags: ["finops", "cheatsheet"],
    author: "Priya Nair",
    summary: "Swipeable carousel thumbnail set summarising top FinOps recommendations.",
    createdAt: "2026-06-08T11:00:00.000Z",
    updatedAt: "2026-07-10T13:25:00.000Z",
    isFavorite: true,
    thumbnailHue: 140,
  },
];
