import type { ScheduledPost, SchedulerNotification } from "@/lib/domain/scheduler";

export type {
  CalendarView,
  QueueSection,
  SchedulePriority,
  ScheduledPost,
  SchedulerNotification,
  ScheduleStatus,
} from "@/lib/domain/scheduler";

/** Reference date for mock data: Aug 2, 2026 */
function at(dayOffset: number, hour: number, minute = 0): string {
  const date = new Date(2026, 7, 2 + dayOffset, hour, minute, 0, 0);
  return date.toISOString();
}

export const SCHEDULED_POSTS: readonly ScheduledPost[] = [
  {
    id: "sch-1",
    title: "Azure Networking Deep Dive",
    platforms: ["linkedin", "medium"],
    scheduledAt: at(0, 9, 0),
    timezone: "America/New_York",
    status: "ready",
    priority: "high",
    thumbnailHue: 210,
    aiVersion: "v2.1",
    approvalStatus: "approved",
    queueOrder: 1,
    hasContent: true,
  },
  {
    id: "sch-2",
    title: "Terraform Modules Best Practices",
    platforms: ["linkedin", "x"],
    scheduledAt: at(0, 14, 30),
    timezone: "America/New_York",
    status: "scheduled",
    priority: "normal",
    thumbnailHue: 145,
    aiVersion: "v1.3",
    approvalStatus: "approved",
    queueOrder: 2,
    hasContent: true,
  },
  {
    id: "sch-3",
    title: "Cloud Run Architecture Patterns",
    platforms: ["youtube", "linkedin"],
    scheduledAt: at(1, 10, 0),
    timezone: "America/New_York",
    status: "scheduled",
    priority: "high",
    thumbnailHue: 45,
    aiVersion: "v3.0",
    approvalStatus: "pending",
    queueOrder: 3,
    hasContent: true,
  },
  {
    id: "sch-4",
    title: "Kubernetes Security Hardening",
    platforms: ["linkedin", "instagram"],
    scheduledAt: at(1, 14, 30),
    timezone: "America/New_York",
    status: "scheduled",
    priority: "normal",
    thumbnailHue: 280,
    aiVersion: "v2.0",
    approvalStatus: "approved",
    queueOrder: 4,
    hasContent: true,
  },
  {
    id: "sch-5",
    title: "Cloud SQL High Availability",
    platforms: ["medium"],
    scheduledAt: at(2, 11, 0),
    timezone: "America/New_York",
    status: "draft",
    priority: "low",
    thumbnailHue: 195,
    aiVersion: "v1.0",
    approvalStatus: "pending",
    queueOrder: 5,
    hasContent: false,
  },
  {
    id: "sch-6",
    title: "IAM Best Practices for Azure",
    platforms: ["linkedin", "facebook"],
    scheduledAt: at(2, 15, 0),
    timezone: "America/New_York",
    status: "scheduled",
    priority: "normal",
    thumbnailHue: 220,
    aiVersion: "v2.2",
    approvalStatus: "approved",
    queueOrder: 6,
    hasContent: true,
  },
  {
    id: "sch-7",
    title: "DevOps Pipeline Automation",
    platforms: ["x", "linkedin"],
    scheduledAt: at(3, 9, 30),
    timezone: "America/New_York",
    status: "ready",
    priority: "high",
    thumbnailHue: 160,
    aiVersion: "v1.5",
    approvalStatus: "approved",
    queueOrder: 7,
    hasContent: true,
  },
  {
    id: "sch-8",
    title: "Azure Landing Zone Launch",
    platforms: ["linkedin"],
    scheduledAt: at(-2, 10, 0),
    timezone: "America/New_York",
    status: "published",
    priority: "high",
    thumbnailHue: 210,
    aiVersion: "v2.1",
    approvalStatus: "approved",
    queueOrder: 8,
    hasContent: true,
  },
  {
    id: "sch-9",
    title: "FinOps Weekly Roundup",
    platforms: ["linkedin", "facebook"],
    scheduledAt: at(-1, 8, 0),
    timezone: "America/New_York",
    status: "published",
    priority: "normal",
    thumbnailHue: 35,
    aiVersion: "v1.2",
    approvalStatus: "approved",
    queueOrder: 9,
    hasContent: true,
  },
  {
    id: "sch-10",
    title: "AKS Workload Identity Guide",
    platforms: ["youtube"],
    scheduledAt: at(4, 16, 0),
    timezone: "America/New_York",
    status: "scheduled",
    priority: "normal",
    thumbnailHue: 265,
    aiVersion: "v2.0",
    approvalStatus: "approved",
    queueOrder: 10,
    hasContent: true,
  },
  {
    id: "sch-11",
    title: "Terraform State Management",
    platforms: ["medium", "linkedin"],
    scheduledAt: at(5, 13, 0),
    timezone: "America/New_York",
    status: "draft",
    priority: "low",
    thumbnailHue: 130,
    aiVersion: "v1.0",
    approvalStatus: "pending",
    queueOrder: 11,
    hasContent: true,
  },
  {
    id: "sch-12",
    title: "Zero Trust Network Access",
    platforms: ["linkedin", "x"],
    scheduledAt: at(0, 14, 30),
    timezone: "America/New_York",
    status: "scheduled",
    priority: "normal",
    thumbnailHue: 300,
    aiVersion: "v1.8",
    approvalStatus: "approved",
    queueOrder: 12,
    hasContent: true,
  },
  {
    id: "sch-13",
    title: "Cloud Cost Optimization Tips",
    platforms: ["instagram"],
    scheduledAt: at(-3, 12, 0),
    timezone: "America/New_York",
    status: "failed",
    priority: "normal",
    thumbnailHue: 50,
    aiVersion: "v1.1",
    approvalStatus: "approved",
    queueOrder: 13,
    hasContent: true,
  },
  {
    id: "sch-14",
    title: "Platform Engineering Overview",
    platforms: ["linkedin"],
    scheduledAt: at(6, 9, 0),
    timezone: "America/New_York",
    status: "scheduled",
    priority: "high",
    thumbnailHue: 180,
    aiVersion: "v2.3",
    approvalStatus: "approved",
    queueOrder: 14,
    hasContent: true,
  },
  {
    id: "sch-15",
    title: "Legacy App Migration Story",
    platforms: ["facebook", "medium"],
    scheduledAt: at(-4, 11, 0),
    timezone: "America/New_York",
    status: "cancelled",
    priority: "low",
    thumbnailHue: 90,
    aiVersion: "v1.0",
    approvalStatus: "rejected",
    queueOrder: 15,
    hasContent: true,
  },
  {
    id: "sch-16",
    title: "Live: Kubernetes Q&A Session",
    platforms: ["youtube", "linkedin"],
    scheduledAt: at(0, 11, 0),
    timezone: "America/New_York",
    status: "publishing",
    priority: "high",
    thumbnailHue: 275,
    aiVersion: "v2.5",
    approvalStatus: "approved",
    queueOrder: 16,
    hasContent: true,
  },
  {
    id: "sch-17",
    title: "Missed: AWS vs Azure Comparison",
    platforms: ["linkedin"],
    scheduledAt: at(-5, 9, 0),
    timezone: "America/New_York",
    status: "failed",
    priority: "normal",
    thumbnailHue: 25,
    aiVersion: "v1.4",
    approvalStatus: "approved",
    queueOrder: 17,
    hasContent: true,
  },
  {
    id: "sch-18",
    title: "Container Security Checklist",
    platforms: ["x", "linkedin"],
    scheduledAt: at(7, 10, 30),
    timezone: "America/New_York",
    status: "scheduled",
    priority: "normal",
    thumbnailHue: 320,
    aiVersion: "v1.6",
    approvalStatus: "approved",
    queueOrder: 18,
    hasContent: true,
  },
];

export const INITIAL_NOTIFICATIONS: readonly SchedulerNotification[] = [
  {
    id: "n-1",
    message: "LinkedIn post scheduled successfully.",
    variant: "success",
    timestamp: at(0, 8, 15),
  },
  {
    id: "n-2",
    message: "Publishing conflict detected for Aug 2 at 2:30 PM.",
    variant: "warning",
    timestamp: at(0, 8, 20),
  },
  {
    id: "n-3",
    message: "Cloud SQL High Availability draft is missing content.",
    variant: "warning",
    timestamp: at(0, 7, 45),
  },
];
