import { COMING_SOON_PLATFORMS } from "@/lib/config/social-accounts";
import type { SocialAccount } from "@/lib/domain/social-account";

export type {
  ActivityEvent,
  ActivityType,
  ConnectionStatus,
  FuturePlatformId,
  HealthStatus,
  SocialAccount,
  SocialAccountFilter,
  SocialPlatformId,
  TokenStatus,
} from "@/lib/domain/social-account";

export const SOCIAL_ACCOUNTS: readonly SocialAccount[] = [
  {
    id: "acc-linkedin",
    platformId: "linkedin",
    platformName: "LinkedIn",
    connectionStatus: "connected",
    healthStatus: "healthy",
    tokenStatus: "active",
    accountName: "Rajasekhar Reddy",
    displayName: "Rajasekhar Reddy",
    username: "rajasekhar-reddy",
    accountType: "Personal profile",
    avatarFallback: "RR",
    avatarHue: 210,
    lastSync: "2026-08-02T13:45:00.000Z",
    connectedSince: "2025-11-12T09:00:00.000Z",
    publishingEnabled: true,
    followers: 18420,
    permissions: ["Publish posts", "Read analytics", "Manage company pages"],
    defaultAudience: "Cloud architects & platform engineers",
    timezone: "America/New_York",
    defaultSettings: {
      visibility: "Public",
      hashtags: "#Azure #CloudArchitecture #DevOps",
      autoPublish: true,
      aiOptimization: true,
      autoSchedule: false,
      urlTracking: true,
    },
  },
  {
    id: "acc-linkedin-co",
    platformId: "linkedin",
    platformName: "LinkedIn",
    connectionStatus: "connected",
    healthStatus: "warning",
    tokenStatus: "expiring_soon",
    accountName: "Cloud Content Hub",
    displayName: "Cloud Content Hub",
    username: "cloud-content-hub",
    accountType: "Company page",
    avatarFallback: "CH",
    avatarHue: 195,
    lastSync: "2026-08-02T11:20:00.000Z",
    connectedSince: "2026-01-08T14:00:00.000Z",
    publishingEnabled: true,
    followers: 5620,
    permissions: ["Publish posts", "Read analytics"],
    defaultAudience: "Enterprise cloud teams",
    timezone: "America/New_York",
    defaultSettings: {
      visibility: "Public",
      hashtags: "#Cloud #SaaS #ContentOps",
      autoPublish: false,
      aiOptimization: true,
      autoSchedule: true,
      urlTracking: true,
    },
  },
  {
    id: "acc-facebook",
    platformId: "facebook",
    platformName: "Facebook",
    connectionStatus: "connected",
    healthStatus: "healthy",
    tokenStatus: "active",
    accountName: "Cloud Content Hub Business",
    displayName: "Cloud Content Hub",
    username: "cloudcontenthub",
    accountType: "Business page",
    avatarFallback: "FB",
    avatarHue: 220,
    lastSync: "2026-08-02T12:10:00.000Z",
    connectedSince: "2026-02-15T10:00:00.000Z",
    publishingEnabled: true,
    followers: 3240,
    permissions: ["Publish posts", "Manage page", "Read insights"],
    defaultAudience: "Marketing & DevOps leaders",
    timezone: "America/New_York",
    defaultSettings: {
      visibility: "Public",
      hashtags: "#CloudComputing",
      autoPublish: true,
      aiOptimization: false,
      autoSchedule: true,
      urlTracking: true,
    },
  },
  {
    id: "acc-instagram",
    platformId: "instagram",
    platformName: "Instagram",
    connectionStatus: "connected",
    healthStatus: "healthy",
    tokenStatus: "active",
    accountName: "cloudcontenthub",
    displayName: "Cloud Content Hub",
    username: "cloudcontenthub",
    accountType: "Creator account",
    avatarFallback: "IG",
    avatarHue: 330,
    lastSync: "2026-08-02T10:30:00.000Z",
    connectedSince: "2026-03-01T16:00:00.000Z",
    publishingEnabled: true,
    followers: 8920,
    permissions: ["Publish feed", "Publish stories", "Read insights"],
    defaultAudience: "Developers & creators",
    timezone: "America/Los_Angeles",
    defaultSettings: {
      visibility: "Public",
      hashtags: "#DevOps #CloudNative #TechTips",
      autoPublish: false,
      aiOptimization: true,
      autoSchedule: true,
      urlTracking: false,
    },
  },
  {
    id: "acc-x",
    platformId: "x",
    platformName: "X (Twitter)",
    connectionStatus: "connected",
    healthStatus: "needs_reauth",
    tokenStatus: "renew_required",
    accountName: "Rajasekhar Reddy",
    displayName: "Rajasekhar Reddy",
    username: "rajasekhar_cloud",
    accountType: "Professional account",
    avatarFallback: "RX",
    avatarHue: 200,
    lastSync: "2026-07-28T18:00:00.000Z",
    connectedSince: "2025-09-20T12:00:00.000Z",
    publishingEnabled: false,
    followers: 12100,
    permissions: ["Post tweets", "Read analytics"],
    defaultAudience: "Cloud & platform engineering",
    timezone: "America/New_York",
    defaultSettings: {
      visibility: "Public",
      hashtags: "#Azure #Kubernetes",
      autoPublish: false,
      aiOptimization: true,
      autoSchedule: false,
      urlTracking: true,
    },
  },
  {
    id: "acc-medium",
    platformId: "medium",
    platformName: "Medium",
    connectionStatus: "connected",
    healthStatus: "healthy",
    tokenStatus: "active",
    accountName: "Cloud Architecture Weekly",
    displayName: "Cloud Architecture Weekly",
    username: "cloud-arch-weekly",
    accountType: "Publication",
    avatarFallback: "MW",
    avatarHue: 140,
    lastSync: "2026-08-02T09:00:00.000Z",
    connectedSince: "2025-12-05T08:00:00.000Z",
    publishingEnabled: true,
    followers: 24600,
    permissions: ["Publish stories", "Edit publication", "View stats"],
    defaultAudience: "Technical readers",
    timezone: "UTC",
    defaultSettings: {
      visibility: "Public",
      hashtags: "",
      autoPublish: true,
      aiOptimization: true,
      autoSchedule: false,
      urlTracking: true,
    },
  },
  {
    id: "acc-youtube",
    platformId: "youtube",
    platformName: "YouTube",
    connectionStatus: "connected",
    healthStatus: "error",
    tokenStatus: "expired",
    accountName: "Cloud Content Hub",
    displayName: "Cloud Content Hub",
    username: "@cloudcontenthub",
    accountType: "Channel",
    avatarFallback: "YT",
    avatarHue: 0,
    lastSync: "2026-07-15T14:00:00.000Z",
    connectedSince: "2025-10-01T11:00:00.000Z",
    publishingEnabled: false,
    followers: 15800,
    permissions: ["Upload videos", "Manage channel", "View analytics"],
    defaultAudience: "Cloud learners",
    timezone: "America/New_York",
    defaultSettings: {
      visibility: "Public",
      hashtags: "#Azure #Terraform #Cloud",
      autoPublish: false,
      aiOptimization: true,
      autoSchedule: false,
      urlTracking: true,
    },
  },
  {
    id: "acc-disconnected",
    platformId: "facebook",
    platformName: "Facebook",
    connectionStatus: "disconnected",
    healthStatus: "warning",
    tokenStatus: "expired",
    accountName: "Legacy DevOps Page",
    displayName: "Legacy DevOps Page",
    username: "legacy-devops",
    accountType: "Business page",
    avatarFallback: "LD",
    avatarHue: 45,
    lastSync: "2026-05-10T08:00:00.000Z",
    connectedSince: null,
    publishingEnabled: false,
    followers: 890,
    permissions: [],
    defaultAudience: "—",
    timezone: "America/New_York",
    defaultSettings: {
      visibility: "Public",
      hashtags: "",
      autoPublish: false,
      aiOptimization: false,
      autoSchedule: false,
      urlTracking: false,
    },
  },
];

export const COMING_SOON_ACCOUNTS: readonly SocialAccount[] = COMING_SOON_PLATFORMS.map(
  (platform, index) => ({
    id: `soon-${platform.id}`,
    platformId: platform.id,
    platformName: platform.label,
    connectionStatus: "disconnected" as const,
    healthStatus: "healthy" as const,
    tokenStatus: "active" as const,
    accountName: platform.label,
    displayName: platform.label,
    username: platform.id,
    accountType: "Coming soon",
    avatarFallback: platform.label.slice(0, 2).toUpperCase(),
    avatarHue: (index * 60 + 120) % 360,
    lastSync: "",
    connectedSince: null,
    publishingEnabled: false,
    followers: 0,
    permissions: [],
    defaultAudience: "—",
    timezone: "UTC",
    defaultSettings: {
      visibility: "Public",
      hashtags: "",
      autoPublish: false,
      aiOptimization: false,
      autoSchedule: false,
      urlTracking: false,
    },
    isComingSoon: true,
  }),
);

export const ACTIVITY_EVENTS = [
  {
    id: "ev-1",
    accountId: "acc-linkedin",
    platformName: "LinkedIn",
    type: "publish_success" as const,
    message: "Azure Landing Zone post published successfully.",
    timestamp: "2026-08-02T14:00:00.000Z",
  },
  {
    id: "ev-2",
    accountId: "acc-youtube",
    platformName: "YouTube",
    type: "publish_failed" as const,
    message: "Video upload failed — token expired.",
    timestamp: "2026-08-01T16:30:00.000Z",
  },
  {
    id: "ev-3",
    accountId: "acc-x",
    platformName: "X (Twitter)",
    type: "permission_changed" as const,
    message: "Write permissions revoked. Reauthentication required.",
    timestamp: "2026-07-28T18:00:00.000Z",
  },
  {
    id: "ev-4",
    accountId: "acc-instagram",
    platformName: "Instagram",
    type: "connected" as const,
    message: "Instagram creator account connected.",
    timestamp: "2026-03-01T16:00:00.000Z",
  },
  {
    id: "ev-5",
    accountId: "acc-disconnected",
    platformName: "Facebook",
    type: "disconnected" as const,
    message: "Legacy DevOps Page disconnected by admin.",
    timestamp: "2026-06-12T10:00:00.000Z",
  },
  {
    id: "ev-6",
    accountId: "acc-medium",
    platformName: "Medium",
    type: "publish_success" as const,
    message: "Terraform Modules article published to publication.",
    timestamp: "2026-07-25T10:00:00.000Z",
  },
  {
    id: "ev-7",
    accountId: "acc-linkedin-co",
    platformName: "LinkedIn",
    type: "permission_changed" as const,
    message: "Analytics scope granted for company page.",
    timestamp: "2026-07-20T09:00:00.000Z",
  },
] satisfies readonly import("@/lib/domain/social-account").ActivityEvent[];
